# Generated by Django 6.0 on 2025-12-31 22:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField()),
                ('date_of_birth', models.CharField()),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('standard_dose', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Medication',
                'indexes': [models.Index(fields=['name'], name='Medication_name_dd604f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_encrypted', models.TextField()),
                ('last_name_encrypted', models.TextField()),
                ('date_of_birth_encrypted', models.TextField()),
                ('gender_encrypted', models.TextField()),
                ('allergies_encrypted', models.TextField(null=True)),
                ('medical_record_number_encrypted', models.TextField()),
                ('hashed_medical_record_number', models.CharField(db_index=True, unique=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'Patient',
                'indexes': [models.Index(fields=['hashed_medical_record_number'], name='Patient_hashed__9a2e86_idx'), models.Index(fields=['is_active'], name='Patient_is_acti_f3fde7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField(db_index=True)),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField()),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_encounter_by_user', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_encounters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_encounter_by_user', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounters', to='patient_management.patient')),
            ],
            options={
                'db_table': 'Encounter',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateField(db_index=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prescription_by_user', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_management.encounter')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_management.medication')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_prescription_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Prescription',
            },
        ),
        migrations.CreateModel(
            name='MedicalAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(db_index=True)),
                ('dose_given', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_nurse', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_prescription', to='patient_management.prescription')),
            ],
            options={
                'db_table': 'MedicalAdministration',
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'visit_datetime'], name='Encounter_patient_adc581_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['doctor', 'visit_datetime'], name='Encounter_doctor__cf971c_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['visit_datetime'], name='Encounter_visit_d_cf4633_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['encounter', 'is_active'], name='Prescriptio_encount_42a7a1_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['start_date'], name='Prescriptio_start_d_cb1f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['is_active'], name='Prescriptio_is_acti_a7fd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaladministration',
            index=models.Index(fields=['prescription', 'administered_at'], name='MedicalAdmi_prescri_8842d6_idx'),
        ),
    ]
